### DISCUSSION TITLE
Docker container

### DISCUSSION THREAD

**Discussion by Ranbato** [borgbase/vorta#1149] [Packaging]
I've created a beta version of Vorta running in a docker container if anyone wants to play with it.
https://hub.docker.com/repository/docker/marklambert/vorta

Here is a sample snippet of my docker-compose.yaml that I am using to start it up.  In the `.env` file I am setting TZ, USER_ID, and GROUP_ID.  I am also defaulting them in the `Dockerfile` to get around [https://github.com/borgbase/vorta/issues/1125](https://github.com/borgbase/vorta/issues/1125)
```
vorta:
    image: marklambert/vorta
    container_name: vorta
    hostname: storage-vorta
    volumes:
      - /volume1/config/vorta:/config
      - /volume1:/data:ro
      - /volumeUSB1/:/destination
    ports:
      - 5811:5800
    restart: unless-stopped
    env_file:
      - ./.env
```

For the curious or paranoid, here are all the scripts: [borg-vorta.zip](https://github.com/borgbase/vorta/files/7771604/borg-vorta.zip)

Suggestions and questions welcome
