### ISSUE TITLE
Please help with the Vorta scheduler.

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#1038]
All i needed is to set up 2 profiles. I need one to be scheduled every 12 hours at 00:00 & 12:00 and the other profile to also be every 12 hours but at 06:00 & 18:00.

This is easy with cron type of scheduling, but there is no way to schedule the second profile (06:00 & 18:00) in Vorta :-(

- I noticed you supplied a command `vorta --create <profile>` so i have tried using that:-
- I have tried to use crontab to execute `vorta --create <profile>` but it errors regarding the qt GUI. (I assume because cron has no DE, I'm just guessing).
- I looked at systemd .timers but a bit complex and i suspect that would error just the same.
- I have tried to make a bash executable script for crontab to execute, but that does not work either.

I really don't want to lose all the benefits and convenience of using Vorta over Borg, but I just can't see how I can schedule it.

**Comment by m3nu** [comment]
The scheduler in the GUI isn't as flexible as Cron and probably never will be.

Using `vorta --create` is the right approach. Just make sure it's run with the same user and a Vorta instance is already running. Then it will trigger the update and you can use any external scheduler.

**Comment by JackDinn** [comment]
I am running from my user crontab and Vorta is running in the tray, but i get this error when crontab is executed automatically by it's schedule. :-
```
Jul 15 12:20:01 greg-inspiron5767 CROND[230964]: (greg) CMDOUT (qt.qpa.xcb: could not connect to display )
Jul 15 12:20:01 greg-inspiron5767 CROND[230964]: (greg) CMDOUT (qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.)
Jul 15 12:20:01 greg-inspiron5767 CROND[230964]: (greg) CMDOUT (This application failed to start because no Qt platform plugin could be initialized. Reinstalling the applic
ation may fix this problem.)
```

**Comment by bastiencyr** [comment]
What is your distribution?
In a terminal, what is the result of 'whereis vorta' ? And in cron script ? On Linux "/use" is not supposed to exist. Maybe you did an error. 
From which package did you install vorta (official, pip, flat...) ? 
Can you run vorta in cron in debug mode (export QT_DEBUG_PLUGINS=1) ? 
And print the user to be sure (whoami) ?
Oufff no more questions 😅

**Comment by JackDinn** [comment]
Im not sure why all the questions as anyone can replicate this by setting up a crontab to execute a profile backup.

However i shall answer what i can.

```
System:
  Kernel: 5.10.49-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 
  parameters: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 
  root=UUID=bfe48f69-800c-4332-b8ea-0df162b1710d rw quiet apparmor=1 
  security=apparmor udev.log_priority=3 
  Desktop: KDE Plasma 5.22.3 tk: Qt 5.15.2 wm: kwin_x11 vt: 1 dm: SDDM 
  Distro: Manjaro Linux base: Arch Linux 
Machine:
  Type: Laptop System: Dell product: Inspiron 5767 v: N/A serial: <filter> 
  Chassis: type: 10 serial: <filter> 
  Mobo: Dell model: 03XWWJ v: A00 serial: <filter> UEFI-[Legacy]: Dell 
  v: 1.4.1 date: 12/24/2020
```

```
❰greg❙~❱✔≻ whereis vorta
vorta: /usr/bin/vorta
```
crontab -e
```
*/1 * * * * whereis vorta
```
journalctl out for the above command:-
```
Jul 21 12:17:01 greg-inspiron5767 CROND[659151]: (greg) CMD (whereis vorta)
Jul 21 12:17:01 greg-inspiron5767 CROND[659150]: (greg) CMDOUT (vorta: /usr/bin/vorta)
Jul 21 12:17:01 greg-inspiron5767 CROND[659150]: (greg) CMDEND (whereis vorta)
```



> On Linux "/use" is not supposed to exist. Maybe you did an error.

Cant answer this question, i dont understand it, however i can tell you that there is no /use file or dir & there is no "use" command on my system.

```
aur/vorta 0.7.7-1 (+32 1.90) (Installed)

❰greg❙~❱✘≻ yay -Qi vorta
Name            : vorta
Version         : 0.7.7-1
Description     : A GUI for BorgBackup
Architecture    : any
URL             : https://github.com/borgbase/vorta
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : borg  python-appdirs  python-apscheduler  python-pyqt5  python-peewee  python-paramiko  python-dateutil  python-secretstorage  python-psutil
                  python-llfuse  python-setuptools
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1496.02 KiB
Packager        : Unknown Packager
Build Date      : Mon 21 Jun 2021 08:50:11 BST
Install Date    : Mon 21 Jun 2021 08:50:21 BST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

*/1 * * * * whoami
```
Jul 21 12:30:01 greg-inspiron5767 CROND[663879]: (greg) CMD (whoami)
Jul 21 12:30:01 greg-inspiron5767 CROND[663878]: (greg) CMDOUT (greg)
```
